name: Node.js Docker Build
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparation
      id: prep
      run: |
        TAGS="ghcr.io/${{ github.repository }}:${{ github.sha }}"
        if [[ $GITHUB_REF == ref/head/master ]]; then
          TAGS="$TAGS,ghcr.io/${{ github.repository }}:latest"
        fi
        echo ::set-output name=tags::${TAGS}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Packages registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ secret.GH_USERNAME }}
        password: ${{ secret.GH_TOKEN }}
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        push: true
        file: src/Dockerfile
        tags: ${{ steps.prep.outputs.tags }}